Add CUDA 11.8
conda-forge/conda-forge-ci-setup-feedstock pull request #207
Opened 2022-10-04 22:29 UTC by m3vaz

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

2022-10-04 22:29 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2022-10-04 22:29 UTC, m3vaz commented
@conda-forge-admin, please rerender

2022-10-05 08:45 UTC, jaimergp commented on recipe/install_cuda.bat
> +if "%CUDA_VERSION%" == "11.8" goto cuda117
```suggestion
if "%CUDA_VERSION%" == "11.8" goto cuda118
```

2022-10-05 08:45 UTC, jaimergp commented on recipe/install_cuda.bat
> +:cuda117
```suggestion
:cuda118
```

2022-10-05 14:28 UTC, kkraus14 approved these changes

2022-10-05 14:52 UTC, jaimergp approved these changes
LGTM. I'd wait before merge given the current Azure incidence.

2022-10-05 18:03 UTC, beckermr requested changes
Please do not merge this pr yet.

2022-10-16 22:45 UTC, m3vaz commented
@beckermr Can we merge this yet?

2022-10-16 23:45 UTC, beckermr commented
No do not merge.

2022-10-19 20:43 UTC, m3vaz commented
From internal discussion, closing until further notice.

2022-10-19 20:43 UTC, closed without merging