disallow uploading from `rattler-build` feedstocks
conda-forge/conda-forge-ci-setup-feedstock pull request #325
Opened 2024-06-27 08:35 UTC by wolfv

Also includes a small refactor to make the `determine_build_tool` function reusable.

2024-06-27 15:10 UTC, beckermr commented on recipe/conda_forge_ci_setup/build_utils.py
> +                "to upload to a label channel"
```suggestion
                "Uploading to conda-forge's main channel is not yet allowed when building with rattler-build.\n"
                "You can set a label channel in the channel_targets section of the config file\n"
                "to upload to a label channel."
```

2024-06-27 15:10 UTC, beckermr approved these changes

2024-06-27 15:11 UTC, beckermr requested changes
Woops! You need to bump the package version in the recipe.

2024-06-27 15:35 UTC, isuruf commented on recipe/conda_forge_ci_setup/build_utils.py
> +        if any(["label/" not in channels]):
```suggestion
        if any(["label/" not in channel for channel in channels]):
```

2024-06-27 20:22 UTC, wolfv commented
I bumped the version and use a generator expression directly plus also checking that the owner is conda-forge.

2024-06-27 20:24 UTC, isuruf commented on recipe/conda_forge_ci_setup/build_utils.py
> +        if any(owner == "conda-forge" and label == "main" for owner, label in channels):
:smile: 
```suggestion
        if ["conda-forge", "main"] in channels:
```

2024-06-27 21:11 UTC, merged

2024-06-27 23:13 UTC, jakirkham commented on recipe/conda_forge_ci_setup/build_utils.py
> +            )
Wonder if we should open an issue to track discussion on this test rollout so we can evaluate when we are ready to enable uploads

2024-06-29 01:54 UTC, jakirkham commented
Looks like all the builds failed on `main`. For [example]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=964384&view=logs&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=b2a8456a-fb11-5506-ca32-5ccd32538dc0&l=1323 ):

```
Failed to upload due to name 'RATTLER_BUILD' is not defined. Trying again in 10 seconds
```

Is this expected?