fix: validation for rattler-build
conda-forge/conda-forge-ci-setup-feedstock pull request #353
Opened 2024-09-26 13:42 UTC by wolfv

I believe this will fix validation for rattler-build. Unfortunately I am not sure how to test this.

2024-09-26 13:46 UTC, wolfv commented
@nichmor or do we need to use `config=...` to pass in a variant config file?

2024-09-26 14:05 UTC, beckermr commented
I'm confused. @jakirkham told me we had correct uploads last night. Is that not true?

2024-09-26 14:20 UTC, wolfv commented
It's true, but the validation fails for recipes that use `stdlib` because we're not passing the variant correctly to rattler-build _during validation_. https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1037882&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3

2024-09-26 15:34 UTC, beckermr requested changes
We need to loop over variants and call render for each separately, accumulating the output metas.

2024-09-27 07:59 UTC, wolfv commented
Trying now in the test recipe repo: https://github.com/conda-forge/jolt-physics-feedstock/pull/4/files

2024-09-27 16:03 UTC, wolfv commented
I tried this on arch' and noarch recipes and it seems to work like a charm :)

2024-09-27 16:05 UTC, beckermr commented
Cool. See my review comment. We need to rearrange the loops now that it is working.

2024-09-27 18:28 UTC, wolfv commented
Do you have an example where there migth be a problem? On the things I tested things were fine.

2024-09-27 19:48 UTC, beckermr approved these changes

2024-09-27 19:53 UTC, beckermr commented
Ack I am sorry @wolfv. I realized we needed to use this function from conda-build. It handles zip keys, extend keys etc.

2024-09-27 19:59 UTC, wolfv commented
Awesome, thanks!

2024-09-27 20:00 UTC, beckermr commented
Can I push the same PR you were using on jolt physics to test?

2024-09-27 20:03 UTC, wolfv commented
Absolutely!

2024-09-27 20:54 UTC, beckermr commented
@conda-forge-admin relint

2024-09-27 20:57 UTC, beckermr commented on recipe/conda_forge_ci_setup/utils.py
> +        print("Final variant is:\n", pprint.pformat(final_variant))
```suggestion
```

2024-09-27 21:18 UTC, beckermr commented
There is a docker outage happening and now there is a truly odd error in the CI logs

```
/home/conda/feedstock_root/build_artifacts/conda-forge-ci-setup_1727470922550/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python: /home/conda/feedstock_root/build_artifacts/conda-forge-ci-setup_1727470922550/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python: cannot execute binary file
```

So yeah maybe we wait until docker is back online?

2024-09-27 21:40 UTC, beckermr commented
@conda-forge-admin relint

2024-09-27 22:29 UTC, beckermr commented
@conda-forge-admin rerender

2024-09-27 22:33 UTC, beckermr commented
there is yet another instability in rerendering in conda-smithy. cc @jaimergp for viz since we've worked on this. argh.

2024-09-27 22:33 UTC, beckermr commented
@conda-forge-admin rerender

2024-09-27 23:07 UTC, merged