Generally enable CUDA 12 cross-compilation
conda-forge/conda-forge-ci-setup-feedstock pull request #363
Opened 2024-10-30 19:14 UTC by jakirkham

As CUDA 12 uses standard conda-forge images and ships a CUDA Toolkit enabled for cross-compilation, there is no need to check for `CDT_NAME` in the CUDA 12 check. Any value conda-forge otherwise supports should also apply to CUDA 12.

CUDA 11 still requires special handling. Though this is not changed here.

<hr>

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2024-10-30 20:03 UTC, jakirkham commented
@conda-forge/core this is ready for review! 😄

2024-10-31 04:20 UTC, h-vetinari requested changes
This doesn't yet do what you want. That whole branch is under
https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/170fdf8adeb07966abd840ab95d269730b36c7ad/recipe/cross_compile_support.sh#L43-L45

which needs adaptation as well e.g. `cdt_name in ["conda", "cos7"]`.

I'd also prefer to fully drop CUDA 11.2 from the setup here. We've [dropped](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5799) it half a year ago, so no need to carry this cruft around anymore IMO.

2024-10-31 04:20 UTC, h-vetinari commented on recipe/cross_compile_support.sh
>              echo "cross compiling with cuda == 11.8 and cdt != cos7/8 not supported yet"
This comment is then also outdated.

2024-10-31 04:20 UTC, h-vetinari commented on recipe/cross_compile_support.sh
>              echo 'cross compiling with cuda not in (11.2, 11.8, 12.*) not supported yet'
same here

2024-11-22 00:12 UTC, jakirkham commented
Closing as this appears to be addressed by PR: https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/365

2024-11-22 00:12 UTC, closed without merging